
name: 'Regenerate code'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'endpoints.yaml'
      - '.github/workflows/generate.yaml'

jobs:
  regenerate_code:
    name: Regenerate code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@master
        with:
          path: 'generate'
      - name: ls -la
        run: ls -la
      - name: Checkout query2app
        uses: actions/checkout@master
        with:
          repository: php-coder/query2app
          path: 'query2app'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: 'query2app'
      - name: ls -la
        run: ls -la
      - name: cd query2app
        run: cd query2app
      - name: ls -la
        run: ls -la
      - name: Install packages
        run: npm ci
      - name: cd generate
        run: cd generate
      - name: Generate python code
        run: ../query2app/src/cli.js --lang python
      - name: Push generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add app.py
          git add routes.py
          git add requirements.txt
          git commit -m "generated"
          git push